"""Harness jobs -- a task KIND dispatching a full agentic CLI run
(SPEC-ASSISTANT.md §9.4, §17 invariants 1-3, AST-070, issue #345,
docs/design/ast-E6.md sequence 3).

A **harness job** (§4 glossary) is distinct from a **turn** (§8): a turn is
one stateless, tool-disabled provider-CLI invocation answering a chat
message (§8.4 -- "harness tool use disabled"); a harness job is a
dispatched, full agentic run of the SAME provider CLIs (§9.4), allowed to
use tools, but under its OWN sandbox posture -- confined to a fresh,
isolated, per-job working directory, never the real filesystem, and never
the assistant repo's own state. This module registers the FIRST real task
kind (`KIND = "harness-job"`) into tasks.py's `executors`/`resolvers` seams
(both deliberately empty before this task -- see tasks.py's own module
docstring); it never touches tasks.py's queue/state-machine plumbing
itself, riding it exactly as designed.

Subprocess discipline (§17 invariants 1-3, reused verbatim from
adapters.py/codex.py/claude.py, never a second invention): argv-array only,
`shell=False`, a mandatory timeout, subscription CLI only (`codex`/
`claude`, the SAME binaries the provider adapters already wrap -- never a
metered API). Unlike `adapters.invoke_cli` (which blocks until the child
exits, `subprocess.run`), a harness job needs to (a) report an
`external_job_id` (see below) BEFORE it finishes -- so a restart mid-job
has something to reconcile against, per §12.4 -- and (b) emit periodic
`task.progress` events while the child is still running, per §9.4's
"report progress" requirement. Neither is expressible through a call that
only returns after the child exits, so this module spawns via
`subprocess.Popen` directly, keeping the exact same `shell=False`/
argv-array/mandatory-timeout posture (a poll loop enforces the timeout by
killing the child, never an unbounded wait) -- this is the same primitive
family, not a second, laxer one.

Own sandbox posture (§9.4, distinct from turns.py's context, Sec8.4):
    - codex: `-s workspace-write` (not turns' `read-only` -- a harness job
      is allowed to actually do work) still `-C <isolated dir>` (bounded to
      a fresh, empty, per-job temp directory -- work products never land
      outside it) plus every other turn-isolation flag (`--ignore-user-
      config`, `--ignore-rules`, `--ephemeral`, an isolated `CODEX_HOME`
      carrying only a copy of `auth.json` -- reusing `codex.
      _isolated_codex_home()` verbatim, the SAME already-researched
      isolation this codebase already vetted, never re-derived here).
    - claude: `--safe-mode` (no CLAUDE.md/plugins/hooks/MCP -- same as a
      turn) but WITHOUT `--tools ""`: a harness job is allowed the CLI's
      normal tool surface, auto-approved via `--permission-mode
      acceptEdits` (headless has no interactive prompt to approve a tool
      call) and bounded to a fresh, isolated `cwd` -- no `CLAUDE_CONFIG_DIR`
      override, same documented reasoning claude.py's own module docstring
      gives (overriding it breaks real auth with no isolation benefit
      `--safe-mode` doesn't already provide).

Threat model (OWNER directive, issue #345's brief -- HARD requirement): an
executor must never persist an `artifact_path` it did not itself construct.
This module NEVER reads a "path"/"artifact_path"-shaped key out of the
dispatched job's stdout, stderr, or any file it wrote in its isolated
workdir -- there is no code path here that even LOOKS for one. The only
`artifact_path` this module ever produces is `_artifact_rel_path(task_id)`,
a pure function of the task's own id (generated by `tasks.enqueue` in the
engine's own process, never influenced by the dispatched job), called
exactly once per outcome. The captured combined stdout+stderr is copied
verbatim into that engine-chosen file; its CONTENT is whatever the harness
CLI produced (that's the point -- it's the run's transcript), but its
LOCATION and NAME are never negotiable.

external_job_id semantics (§12.4, AST-067's resolver contract) -- a
locally-spawned harness run has no remote system to poll, so this module
answers §12.4's "re-poll... before any resubmission" with a PID plus a
durable, atomically-written completion marker file under the task's own
state dir (`_job_state_dir`, keyed by task_id -- NOT external_job_id,
because task_id is what actually identifies "this task's own state",
per the OWNER directive's wording): `external_job_id` is
`"{task_id}:{pid}"` (see `_encode_external_job_id`/`_decode_external_job_id`)
so a resolver -- which per tasks.py's contract receives ONLY
`(external_job_id, payload)`, never `task_id` -- can still recover the
state-dir key. `resolve_harness_job` reads the marker if one exists
(the job finished, one way or another -- its recorded state wins,
regardless of whether the pid is still around, e.g. reused by an unrelated
later process); otherwise it checks pid liveness (`_pid_alive`): alive ->
"in_progress" (genuinely still running, matches AST-067's contract exactly
-- never resubmitted); not alive and no marker -> "not_found" (the
process is gone and left no trace -- this locally-spawned job's honest
equivalent of "the remote system has no record of it", AST-067's own
wording for that resolver outcome). A malformed/unparseable
`external_job_id` (should never happen from THIS module's own dispatch,
but a resolver must never trust its input) degrades to "not_found" the
same way, for the same reason: nothing to look up.

Known, documented gap (flagged, same posture as codex.py/claude.py's own
DOCUMENTED GAP sections): raw pid liveness can theoretically false-positive
if the OS recycles a pid between an engine crash and the next restart's
reconciliation pass, in the narrow window before the completion marker
would have been written. This module does not attempt process-identity
verification beyond `os.kill(pid, 0)` (no `/proc` cmdline cross-check,
which is not portably available on macOS) -- a future task can harden this
if it proves to matter; it does not undermine §12.4's actual invariant
(never resubmit), since a false "in_progress" degrades to "still show as
running", never to a duplicate submission.
"""
import json
import os
import re
import shutil
import subprocess
import tempfile
import time

from assistant import artifacts, codex as codex_adapter, tasks

KIND = "harness-job"

TASKS_STATE_DIR_REL = os.path.join(".claude", "assistant", "tasks")  # same
# .claude/assistant/ tree tasks.sqlite/artifacts/ already live under --
# already covered by local-state.manifest's directory-level `ignore
# .claude/assistant/` entry (artifacts.py's own module docstring makes the
# identical observation for its sibling ARTIFACTS_DIR_REL).

RESULT_MARKER_NAME = "result.json"

DEFAULT_HARNESS_TIMEOUT_SECONDS = 300  # a harness job is a full agentic
# run, not a single turn -- generous relative to adapters.py's 60s
# DEFAULT_TIMEOUT_SECONDS, still bounded (Sec8.5/N5: every subprocess call
# has a mandatory timeout, no exceptions).
MIN_HARNESS_TIMEOUT_SECONDS = 1
MAX_HARNESS_TIMEOUT_SECONDS = 1800  # 30 min -- round-1 review MINOR (c),
# issue #345: "generous" must never mean "unbounded"; §17's mandatory-
# timeout posture applies to every subprocess call, harness jobs included.
DEFAULT_POLL_INTERVAL_SECONDS = 2.0
MIN_POLL_INTERVAL_SECONDS = 0.01

_SUPPORTED_PROVIDERS = ("codex", "claude")

# round-1 review MINOR (d), issue #345: task ids this module itself mints
# are uuid4 hex (tasks.enqueue), but `_decode_external_job_id` parses a
# STRING that will be used to build an on-disk path
# (`_job_state_dir`/`_marker_path`) -- a resolver must validate the shape
# BEFORE it ever reaches os.path.join, not rely on "well-formed in
# practice". No `/` and no `..` are possible through this allowlist.
_TASK_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


class HarnessJobError(Exception):
    """Raised by `run_harness_job` for any failure this module can
    classify specifically (bad payload, unsupported provider, timeout,
    nonzero exit) -- caught by tasks.py's `_process_create` exactly like
    any other executor exception, recorded as the row's `error` text."""


# --------------------------------------------------------------------
# external_job_id encode/decode -- see module docstring.
# --------------------------------------------------------------------

def _encode_external_job_id(task_id, pid):
    return f"{task_id}:{pid}"


def _decode_external_job_id(external_job_id):
    """Returns `(task_id, pid)` or raises ValueError -- a resolver-side
    parse, so callers (`resolve_harness_job`) treat a raise as "cannot
    identify this job", never a crash (see that function). The decoded
    `task_id` is validated against `_TASK_ID_RE` (round-1 review MINOR d,
    issue #345) BEFORE it is ever used to build `_job_state_dir`/
    `_marker_path` -- an external_job_id is untrusted input the instant it
    crosses back through a restart, and a `/` or `..` inside it would
    otherwise become a real path-traversal primitive. `pid` must be a
    positive integer: pid 0 is meaningless (and `os.kill(0, 0)` targets the
    whole process group, not a specific job) and a negative pid is not a
    real process id at all."""
    if not isinstance(external_job_id, str) or ":" not in external_job_id:
        raise ValueError(f"malformed external_job_id: {external_job_id!r}")
    task_id, _, pid_text = external_job_id.rpartition(":")
    if not task_id or not _TASK_ID_RE.match(task_id):
        raise ValueError(f"malformed external_job_id (invalid task id): {external_job_id!r}")
    if not pid_text.isdigit():
        raise ValueError(f"malformed external_job_id (invalid pid): {external_job_id!r}")
    pid = int(pid_text)
    if pid <= 0:
        raise ValueError(f"malformed external_job_id (non-positive pid): {external_job_id!r}")
    return task_id, pid


def _job_state_dir(root, task_id):
    return os.path.join(root, TASKS_STATE_DIR_REL, task_id)


def _marker_path(root, task_id):
    return os.path.join(_job_state_dir(root, task_id), RESULT_MARKER_NAME)


def _artifact_rel_path(task_id):
    """The ONLY function in this module that produces an `artifact_path`
    value -- a pure function of the task's own id (see module docstring's
    threat-model section). Called exactly once per outcome; its result is
    NEVER combined with, or overridden by, anything read from the
    dispatched job's own output."""
    return f"{task_id}.log"


def _write_marker(root, task_id, marker):
    """Atomic write (temp file + os.replace, same discipline this
    codebase's other durable-state writers use) -- a restart-time resolver
    must never observe a half-written marker file."""
    state_dir = _job_state_dir(root, task_id)
    os.makedirs(state_dir, exist_ok=True)
    marker_path = _marker_path(root, task_id)
    fd, tmp_path = tempfile.mkstemp(prefix="result-", suffix=".json.tmp", dir=state_dir)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(marker, fh, sort_keys=True)
        os.replace(tmp_path, marker_path)
    except Exception:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise


def _pid_alive(pid):
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True  # exists, just not ours -- still "alive" from here
    except OSError:
        return False
    return True


# --------------------------------------------------------------------
# argv construction -- own sandbox posture (module docstring).
# --------------------------------------------------------------------

def _isolated_workdir():
    return tempfile.mkdtemp(prefix="harness-job-")


def _build_argv(provider, model, workdir, prompt):
    if provider == "codex":
        return [
            "codex", "exec",
            "--json",
            "-s", "workspace-write",
            "--skip-git-repo-check",
            "--ignore-user-config",
            "--ignore-rules",
            "--ephemeral",
            "-m", model,
            "-C", workdir,
            prompt,
        ]
    if provider == "claude":
        return [
            "claude",
            "-p",
            "--output-format", "json",
            "--strict-mcp-config",
            "--permission-mode", "acceptEdits",
            "--no-session-persistence",
            "--safe-mode",
            "--model", model,
            prompt,
        ]
    raise HarnessJobError(
        f"unsupported harness provider {provider!r} (known: {', '.join(_SUPPORTED_PROVIDERS)})"
    )


def _build_env(provider, isolated_workdir_cleanup):
    """Returns `(env, cleanup_dirs)`. codex gets an isolated CODEX_HOME
    (reusing codex.py's already-vetted `_isolated_codex_home` verbatim --
    module docstring's "own sandbox posture" section); claude gets NO
    env-home override, same documented reasoning claude.py's module
    docstring itself gives."""
    env = dict(os.environ)
    cleanup_dirs = list(isolated_workdir_cleanup)
    if provider == "codex":
        codex_home = codex_adapter._isolated_codex_home()
        env["CODEX_HOME"] = codex_home
        cleanup_dirs.append(codex_home)
    return env, cleanup_dirs


def _validate_number(value, name, *, minimum, maximum):
    """Round-1 review MINOR (c), issue #345: bool-before-int-guard (a bare
    `isinstance(value, (int, float))` would silently accept `True`/`False`
    as valid numbers) then a closed `[minimum, maximum]` bounds check.
    Raises `HarnessJobError` with a specific message; never lets a bad
    value reach the poll loop's arithmetic as a raw TypeError/nonsensical
    comparison."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise HarnessJobError(
            f"harness-job payload {name!r} must be a number (got {type(value).__name__})"
        )
    if not (minimum <= value <= maximum):
        raise HarnessJobError(
            f"harness-job payload {name!r} must be between {minimum} and {maximum} (got {value!r})"
        )
    return value


def _validate_payload(payload):
    """Returns `(root, provider, prompt, model, timeout_seconds,
    poll_interval)` or raises `HarnessJobError` -- every field this
    executor needs, fully validated BEFORE anything is spawned (round-1
    review MINOR c, issue #345: `timeoutSeconds`/`pollIntervalSeconds`
    used to be read with a bare `.get(...) or DEFAULT`, with no type/bounds
    checking at all)."""
    if not isinstance(payload, dict):
        raise HarnessJobError("harness-job payload must be a mapping")
    root = payload.get("root")
    if not isinstance(root, str) or not root:
        raise HarnessJobError("harness-job payload missing required 'root'")
    provider = payload.get("provider")
    if provider not in _SUPPORTED_PROVIDERS:
        raise HarnessJobError(
            f"harness-job payload 'provider' must be one of {_SUPPORTED_PROVIDERS} (got {provider!r})"
        )
    prompt = payload.get("prompt")
    if not isinstance(prompt, str) or not prompt:
        raise HarnessJobError("harness-job payload missing required 'prompt'")
    model = payload.get("model")
    if not isinstance(model, str) or not model:
        raise HarnessJobError("harness-job payload missing required 'model'")

    timeout_seconds = payload.get("timeoutSeconds")
    if timeout_seconds is None:
        timeout_seconds = DEFAULT_HARNESS_TIMEOUT_SECONDS
    else:
        timeout_seconds = _validate_number(
            timeout_seconds, "timeoutSeconds",
            minimum=MIN_HARNESS_TIMEOUT_SECONDS, maximum=MAX_HARNESS_TIMEOUT_SECONDS,
        )

    poll_interval = payload.get("pollIntervalSeconds")
    if poll_interval is None:
        poll_interval = DEFAULT_POLL_INTERVAL_SECONDS
    else:
        poll_interval = _validate_number(
            poll_interval, "pollIntervalSeconds",
            minimum=MIN_POLL_INTERVAL_SECONDS, maximum=timeout_seconds,
        )

    return root, provider, prompt, model, timeout_seconds, poll_interval


# --------------------------------------------------------------------
# The executor (tasks.py `executors` seam).
# --------------------------------------------------------------------

def run_harness_job(payload, report_progress):
    """`executors[KIND]` -- see module docstring. Blocks the tasks worker
    thread until the dispatched CLI exits or the timeout fires (tasks.py's
    documented single-serial-thread execution model already accepts this;
    it is what keeps chat/turns un-blocked, §9.5 -- this thread is not
    that one). Returns `{"artifact_path": ..., "result": {...}}` on
    success; raises `HarnessJobError` on any failure (unsupported
    provider, malformed payload, timeout, nonzero exit) -- caught by
    `tasks._process_create` exactly like any other executor's exception."""
    task_id = getattr(report_progress, "task_id", None)
    if not task_id:
        # Defensive, not user-facing: this executor is only ever meant to
        # run via tasks.run_worker's `_process_create`, which always sets
        # this attribute (see tasks.py's "AST-070 extension seam").
        raise HarnessJobError(
            "run_harness_job requires a task-scoped report_progress "
            "(missing .task_id attribute) -- it must only run via tasks.run_worker"
        )
    root, provider, prompt, model, timeout_seconds, poll_interval = _validate_payload(payload)

    workdir = _isolated_workdir()
    stdout_path = os.path.join(workdir, ".harness-output.log")
    env, cleanup_dirs = _build_env(provider, [workdir])
    argv = _build_argv(provider, model, workdir, prompt)

    proc = None
    returncode = None
    timeout_error = None
    try:
        try:
            with open(stdout_path, "wb") as stdout_fh:
                # Popen, not invoke_cli/subprocess.run -- see module
                # docstring: this call needs the pid BEFORE the child exits
                # (to persist external_job_id promptly) and needs to poll
                # for progress instead of blocking once. shell=False and an
                # enforced timeout (the poll loop below) preserve the SAME
                # invariants invoke_cli enforces for every other subprocess
                # call.
                proc = subprocess.Popen(
                    argv, cwd=workdir, env=env, stdin=subprocess.DEVNULL,
                    stdout=stdout_fh, stderr=subprocess.STDOUT, shell=False,
                )
                external_job_id = _encode_external_job_id(task_id, proc.pid)
                report_progress({"stage": "started", "pid": proc.pid, "pct": 0}, external_job_id=external_job_id)

                start = time.monotonic()
                last_progress = start
                while True:
                    ret = proc.poll()
                    if ret is not None:
                        break
                    now = time.monotonic()
                    if now - start > timeout_seconds:
                        proc.kill()
                        try:
                            proc.wait(timeout=5)
                        except subprocess.TimeoutExpired:
                            pass
                        timeout_error = (
                            f"harness job (provider={provider}) exceeded {timeout_seconds}s "
                            f"timeout, killed pid {proc.pid}"
                        )
                        break  # fall through to the SAME publish/marker
                        # logic every other exit path uses (round-1 review
                        # MINOR a, issue #345) -- a bare early `raise` here
                        # used to skip publishing entirely, so the outer
                        # cleanup's workdir wipe destroyed the only copy of
                        # exactly the transcript a human would most want to
                        # debug a timeout with.
                    if now - last_progress >= poll_interval:
                        # Round-1 review MINOR (e): an honest, timeout-
                        # derived pct -- there is no native progress signal
                        # for an agentic run, so elapsed/timeout is the
                        # best available proxy (documented in
                        # docs/spec-deltas/345.md); capped at 99 so it
                        # never claims "done" before the completed/failed
                        # transition actually happens.
                        pct = min(99, round(100 * (now - start) / timeout_seconds))
                        report_progress(
                            {"stage": "running", "elapsed_seconds": round(now - start, 1), "pct": pct},
                            external_job_id=external_job_id,
                        )
                        last_progress = now
                    time.sleep(min(0.2, poll_interval))
            if timeout_error is None:
                returncode = proc.returncode
        finally:
            if proc is not None and proc.poll() is None:
                try:
                    proc.kill()
                    proc.wait(timeout=5)
                except Exception:
                    pass

        try:
            with open(stdout_path, "r", encoding="utf-8", errors="replace") as fh:
                output_text = fh.read()
        except OSError:
            output_text = ""

        artifact_rel_path = _artifact_rel_path(task_id)
        # Published UNCONDITIONALLY -- success, nonzero exit, OR timeout
        # (round-1 review MINOR a/b, issue #345): the captured transcript
        # is written to its permanent home before the outer `finally`
        # removes `workdir`, regardless of how this run ends, so a failed/
        # timed-out job's output is never silently lost. It is not,
        # however, advertised as `artifact_path` for a failed/timeout
        # outcome (see below) -- `artifacts.resolve()` only ever serves a
        # COMPLETED task's artifact (Sec12.2/AST-068, untouched by this
        # task); see docs/spec-deltas/345.md for the "record it, but not
        # yet servable" decision this represents.
        _publish_artifact(root, artifact_rel_path, output_text)

        summary = output_text.strip()
        if len(summary) > 2000:
            summary = summary[:2000] + "... (truncated)"

        if timeout_error is not None:
            # Written here (not just raised) so a restart-time resolver
            # finds a durable "failed" record instead of falling through
            # to pid-liveness/not_found for a job this process already
            # knows the fate of. Marker carries only state/error/result
            # (round-1 review BLOCKER, issue #345) -- see resolve_
            # harness_job's docstring for why artifact_path is never one
            # of the fields a marker is trusted to carry.
            _write_marker(root, task_id, {"state": "failed", "error": timeout_error})
            raise HarnessJobError(timeout_error)

        if returncode != 0:
            error = f"harness job (provider={provider}) exited {returncode}"
            _write_marker(root, task_id, {"state": "failed", "error": error})
            raise HarnessJobError(error)

        result = {"returncode": returncode, "summary": summary}
        # Marker carries only state/result (round-1 review BLOCKER, issue
        # #345) -- NEVER artifact_path. See resolve_harness_job's
        # docstring: the served path is always rebuilt from the decoded
        # task_id, never read back out of stored state.
        _write_marker(root, task_id, {"state": "completed", "result": result})
        return {"artifact_path": artifact_rel_path, "result": result}
    finally:
        # Cleanup runs on EVERY exit path (success, nonzero exit, timeout,
        # or any unexpected exception) -- the isolated workdir/CODEX_HOME
        # must never leak regardless of how this function returns. Always
        # runs AFTER the publish step above, so the transcript's permanent
        # copy exists before its temporary source is removed.
        for d in cleanup_dirs:
            _rmtree_ignore(d)


def _rmtree_ignore(path):
    shutil.rmtree(path, ignore_errors=True)


def _publish_artifact(root, artifact_rel_path, content_text):
    """Writes `content_text` (the captured, engine-controlled combined
    stdout+stderr transcript) into `root`'s artifacts dir at
    `artifact_rel_path` -- the SAME `.claude/assistant/artifacts/` tree
    `artifacts.py`'s `resolve()` serves from (`artifacts.ARTIFACTS_DIR_REL`,
    reused, not re-derived)."""
    artifacts_root = os.path.join(root, artifacts.ARTIFACTS_DIR_REL)
    os.makedirs(artifacts_root, exist_ok=True)
    dest = os.path.join(artifacts_root, artifact_rel_path)
    fd, tmp_path = tempfile.mkstemp(prefix="artifact-", dir=artifacts_root)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content_text)
        os.replace(tmp_path, dest)
    except Exception:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise


# --------------------------------------------------------------------
# The resolver (tasks.py `resolvers` seam, AST-067 restart reconciliation).
# --------------------------------------------------------------------

def resolve_harness_job(external_job_id, payload):
    """`resolvers[KIND]` -- see module docstring's "external_job_id
    semantics" section. Never raises for a routine "cannot identify this
    job" case (a malformed id, a missing root in payload) -- degrades to
    `not_found`, a recognized outcome tasks.py's `_reconcile_row` already
    orphans specifically; only a genuinely unexpected internal error
    (e.g. a marker file that exists but is not even valid JSON after the
    atomic-write discipline above -- should not happen) is allowed to
    raise, which `_reconcile_row` also handles (orphaned, "resolver
    raised"). NEVER resubmits anything -- this function only reads.

    OWNER threat-model directive, round-1 review BLOCKER (issue #345): a
    completed outcome's `artifact_path` is ALWAYS `_artifact_rel_path
    (task_id)`, rebuilt fresh from the task id THIS function itself just
    decoded -- never `marker.get("artifact_path")`, even though this
    module's own `run_harness_job` no longer writes that key at all. A
    marker file is stored state that survives a restart; once state
    crosses that boundary it is untrusted the same way any other executor-
    boundary value is (§17.11) -- a tampered, buggy, or simply legacy-
    shaped marker naming a DIFFERENT real task's file (still safely INSIDE
    the artifacts root, so `artifacts.resolve()`'s escape check alone would
    never catch it) must never be able to redirect what a victim task's
    `/assistant/artifact/<task_id>` serves. `result` is passed through
    as-is (it is rendered text, not a filesystem path -- see docs/spec-
    deltas/345.md for why that is a materially different trust question)."""
    try:
        task_id, pid = _decode_external_job_id(external_job_id)
    except ValueError:
        return {"state": "not_found"}

    root = payload.get("root") if isinstance(payload, dict) else None
    if not isinstance(root, str) or not root:
        return {"state": "not_found"}

    marker_path = _marker_path(root, task_id)
    if os.path.isfile(marker_path):
        try:
            with open(marker_path, "r", encoding="utf-8") as fh:
                marker = json.load(fh)
        except (OSError, ValueError):
            marker = None
        if isinstance(marker, dict) and marker.get("state") in ("completed", "failed"):
            if marker["state"] == "completed":
                return {
                    "state": "completed",
                    "artifact_path": _artifact_rel_path(task_id),
                    "result": marker.get("result"),
                }
            return {"state": "failed", "error": marker.get("error") or "harness job failed"}
        # marker present but unusable -- fall through to liveness, the job
        # may still genuinely be running (a marker is only ever written
        # AFTER the child exits).

    if _pid_alive(pid):
        return {"state": "in_progress"}
    return {"state": "not_found"}


# --------------------------------------------------------------------
# Dispatch helper -- a convenience wrapper around tasks.enqueue for future
# callers (e.g. a capability invocation, out of THIS task's scope per the
# issue #345 brief's non-scope list) so every harness-job payload is built
# the one, consistent way this module's own executor/resolver expect.
# --------------------------------------------------------------------

def dispatch(q, root, *, provider, model, prompt, turn_id=None,
             timeout_seconds=None, poll_interval_seconds=None):
    """Enqueues one harness job -- thin wrapper over `tasks.enqueue`
    (enqueue-only, never raises into the caller, returns `task_id` or
    `None` exactly like `tasks.enqueue` itself; see that function's
    docstring)."""
    payload = {"root": root, "provider": provider, "model": model, "prompt": prompt}
    if timeout_seconds is not None:
        payload["timeoutSeconds"] = timeout_seconds
    if poll_interval_seconds is not None:
        payload["pollIntervalSeconds"] = poll_interval_seconds
    return tasks.enqueue(q, root, KIND, payload=payload, turn_id=turn_id)
