#!/usr/bin/env python3
"""changelog.py — deterministic CHANGELOG.md generator anchored on the
spec-workflow plugin's semver history (#404).

CLI:
    changelog.py generate [--repo <path>] [--output <path>] [--ref <ref>]
        Regenerates the ENTIRE CHANGELOG.md at <output> (default:
        <repo>/CHANGELOG.md) from <repo>'s git history, walking
        `git log --first-parent <ref>` (default: HEAD). Full idempotent
        regeneration every run — there is no incremental append mode; the
        same input history always produces byte-identical output. This is
        deliberate: a dumb GitHub Action (.github/workflows/changelog.yml)
        re-runs this on every push to main and commits the result only when
        it actually changed.

VERSION ANCHORING
    The plugin version lives in
    ``plugins/spec-workflow/.claude-plugin/plugin.json`` (the ``version``
    field) and is bumped IN-COMMIT by the #400 semver pipeline
    (``scripts/semver.sh``) at squash-merge time — the same commit that
    lands the feature/fix ALSO carries the version bump. We walk
    ``git log --first-parent <HEAD>`` (oldest to newest) and, for every
    commit, read plugin.json's ``version`` AS OF that commit (i.e. the tree
    that results from applying the commit — ``git show <sha>:<path>``). A
    commit "belongs" to the version its own tree reports: since the bump is
    folded into the same commit as the change it accompanies, that is the
    version a reader encountering that commit's effects would see. Runs of
    consecutive commits reporting the same version form that version's
    window; windows are rendered newest-first.

    plugin.json predates some commits (or the file/version never changes
    for a stretch) — those commits bucket under the OLDEST version we ever
    observe in the whole walk ("history predating plugin.json ... buckets
    under the oldest known version"). If plugin.json is never found at all
    (a degenerate/test-only history), everything buckets under a single
    synthetic UNVERSIONED_LABEL window so the tool never crashes — rendered
    as a literal ``## Unversioned — <date>`` heading (NOT run through the
    ``v<version>`` template, which would otherwise mangle the sentinel into
    a malformed ``## vunversioned — <date>``).

    The old ``spec-workflow--v0.3.0`` .. ``spec-workflow--v0.6.1`` git tags
    are NOT consulted — plugin.json diffs are the sole authority, per spec.

ENTRY SOURCE
    Each first-parent commit's subject (first line) + body (the rest).
    Squash-merge commits' messages ARE the merge descriptions, so the body
    is exactly what a human wrote about the merged change. The body is
    included as the entry's expandable detail, trimmed of trailer lines
    (``Applied-by:``, ``Reviewed-by:``, ``Co-authored-by:``,
    ``Co-Authored-By:`` — matched case-insensitively at line start) and of
    leading/trailing blank lines.

CLASSIFICATION
    The subject is parsed as a conventional-commit header:
    ``type(scope)!?: description``. Recognized types are grouped, in this
    FIXED output order:
        Features        feat
        Fixes           fix
        Performance     perf
        Refactoring     refactor
        Documentation   docs
        Tests           test, tests
        CI/Build        ci, build
        Chores          chore, style
        Other           anything else — including a recognized-but-unlisted
                         conventional type, and any subject that doesn't
                         parse as conventional at all.
    A ``!`` before the colon (breaking-change marker) does not change
    grouping — only #400's semver classifier cares about it.

EXCLUSIONS — workflow process noise, meaningless to a changelog reader.
    A commit whose subject STARTS WITH any of these literal prefixes is
    dropped entirely (never emitted, in no group):
        retro:             retro+feedback:     feedback:
        brain:              config:
        chore(changelog):
    The LAST one is load-bearing for the GitHub Action's loop-safety: the
    Action's own commits use exactly that subject
    (``chore(changelog): regenerate``, see .github/workflows/changelog.yml).
    Because this generator excludes its own commit kind from the very
    history it reads, a regeneration that only sees a prior
    ``chore(changelog): regenerate`` commit added since its last run
    produces BYTE-IDENTICAL output to before — no diff, no new commit, no
    infinite trigger loop. Every other exclusion above is ordinary
    process-noise hygiene; this one is a correctness property.

OUTPUT FORMAT (documented precisely — #405 renders this file as a per-
version expandable web UI and depends on this exact structure):

    # Changelog

    <!-- GENERATED by plugins/spec-workflow/scripts/changelog.py — do not edit by hand. -->

    ## v0.30.1 — 2026-07-25

    ### Features
    - **scope:** description (`abc1234`)
      > first body line
      > second body line

    ### Fixes
    - ...

    ## v0.30.0 — 2026-07-20

    ...

  - Exactly one ``##`` heading per version, NEWEST first.
  - Heading text: ``v<version> — <date>`` (em dash, spaces around it); date
    is YYYY-MM-DD, the date of the NEWEST commit in that version's window.
  - Exactly one ``###`` heading per NON-EMPTY group, in the fixed group
    order above.
  - One bullet per commit: ``- **<scope>:** <description> (`<shorthash>`)``
    when the subject carried a scope, else ``- <description> (`<shorthash>`)``.
    A non-conventional subject renders its whole subject as <description>
    with no scope. Issue/PR references already embedded in the subject
    (e.g. ``(#400)``) are left as-is, verbatim, inside <description>.
  - When the trailer-stripped body is non-empty, its lines follow the
    bullet, each indented two spaces and prefixed ``> ``.
"""
import json
import os
import re
import subprocess
import sys

PLUGIN_JSON_REL = os.path.join(
    "plugins", "spec-workflow", ".claude-plugin", "plugin.json"
)

RS = "\x1e"  # record separator between commits
FS = "\x1f"  # field separator between fields within a commit

EXCLUDED_PREFIXES = (
    "retro:",
    "retro+feedback:",
    "feedback:",
    "brain:",
    "config:",
    "chore(changelog):",  # loop-safety — see module docstring
)

TRAILER_RE = re.compile(
    r"^(Applied-by|Reviewed-by|Co-authored-by|Co-Authored-By)\s*:",
    re.IGNORECASE,
)

CONVENTIONAL_RE = re.compile(
    r"^(?P<type>[A-Za-z0-9_-]+)(\((?P<scope>[^)]*)\))?(?P<breaking>!)?:\s*(?P<desc>.*)$"
)

# Sentinel version bucket for the degenerate case where plugin.json is never
# found anywhere in the walked history — not a real semver string, so
# rendering must NOT run it through the "v<version>" heading template (see
# render_version_section).
UNVERSIONED_LABEL = "unversioned"

# Fixed group order + membership. "Other" is not listed here; it's the
# fallback for anything not claimed by another group.
GROUP_ORDER = [
    "Features",
    "Fixes",
    "Performance",
    "Refactoring",
    "Documentation",
    "Tests",
    "CI/Build",
    "Chores",
    "Other",
]
TYPE_TO_GROUP = {
    "feat": "Features",
    "fix": "Fixes",
    "perf": "Performance",
    "refactor": "Refactoring",
    "docs": "Documentation",
    "test": "Tests",
    "tests": "Tests",
    "ci": "CI/Build",
    "build": "CI/Build",
    "chore": "Chores",
    "style": "Chores",
}


class Commit:
    __slots__ = ("sha", "short", "date", "subject", "body")

    def __init__(self, sha, short, date, subject, body):
        self.sha = sha
        self.short = short
        self.date = date
        self.subject = subject
        self.body = body


def _run_git(repo, args):
    return subprocess.run(
        ["git", "-C", repo] + args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def first_parent_log(repo, ref="HEAD"):
    """Return Commit objects for `git log --first-parent`, OLDEST first."""
    fmt = f"%H{FS}%h{FS}%ad{FS}%s{FS}%b{RS}"
    proc = _run_git(
        repo,
        [
            "log",
            "--first-parent",
            "--reverse",
            "--date=format:%Y-%m-%d",
            f"--pretty=format:{fmt}",
            ref,
        ],
    )
    if proc.returncode != 0:
        return []
    raw = proc.stdout.decode("utf-8", errors="replace")
    commits = []
    for rec in raw.split(RS):
        if not rec.strip("\n"):
            continue
        parts = rec.split(FS)
        if len(parts) < 5:
            continue
        sha, short, date, subject, body = parts[0], parts[1], parts[2], parts[3], parts[4]
        # rec may carry a leading newline left over from the previous
        # record's terminator; strip it defensively.
        sha = sha.lstrip("\n")
        body = body.strip("\n")
        commits.append(Commit(sha, short, date, subject, body))
    return commits


def plugin_json_version(repo, sha):
    """Version string in plugin.json at `sha`, or None if absent/unreadable."""
    proc = _run_git(repo, ["show", f"{sha}:{PLUGIN_JSON_REL}"])
    if proc.returncode != 0:
        return None
    try:
        data = json.loads(proc.stdout.decode("utf-8", errors="replace"))
    except ValueError:
        return None
    v = data.get("version")
    return v if isinstance(v, str) and v else None


def build_version_windows(repo, commits):
    """Group `commits` (oldest-first) into (version, [commits]) windows,
    oldest-first. See module docstring for the bucketing rules."""
    versions = [plugin_json_version(repo, c.sha) for c in commits]

    first_known = None
    for v in versions:
        if v is not None:
            first_known = v
            break

    if first_known is None:
        # plugin.json never found anywhere in this history.
        return [(UNVERSIONED_LABEL, commits)] if commits else []

    resolved = []
    last_seen = first_known
    for v in versions:
        if v is None:
            # predates plugin.json, or a stretch where it's unreadable —
            # carry forward the last known version (which, before the
            # first known version ever appears, IS first_known).
            resolved.append(last_seen)
        else:
            last_seen = v
            resolved.append(v)

    windows = []
    cur_version = None
    cur_commits = []
    for c, v in zip(commits, resolved):
        if v != cur_version:
            if cur_commits:
                windows.append((cur_version, cur_commits))
            cur_version = v
            cur_commits = []
        cur_commits.append(c)
    if cur_commits:
        windows.append((cur_version, cur_commits))
    return windows


def is_excluded(subject):
    return any(subject.startswith(p) for p in EXCLUDED_PREFIXES)


def classify(subject):
    """Return (group, scope_or_None, description)."""
    m = CONVENTIONAL_RE.match(subject)
    if not m:
        return "Other", None, subject
    ctype = m.group("type").lower()
    scope = m.group("scope") or None
    desc = m.group("desc")
    group = TYPE_TO_GROUP.get(ctype, "Other")
    if group == "Other":
        # Not a recognized type — Other bullets render the whole original
        # subject, not a stripped description, since we can't be confident
        # the ":" split is even a real conventional-commit header.
        return "Other", None, subject
    return group, scope, desc


def strip_trailers(body):
    lines = body.split("\n") if body else []
    kept = [ln for ln in lines if not TRAILER_RE.match(ln.strip())]
    # trim leading/trailing blank lines
    while kept and kept[0].strip() == "":
        kept.pop(0)
    while kept and kept[-1].strip() == "":
        kept.pop()
    return kept


def render_entry(c):
    group, scope, desc = classify(c.subject)
    if scope:
        bullet = f"- **{scope}:** {desc} (`{c.short}`)"
    else:
        bullet = f"- {desc} (`{c.short}`)"
    lines = [bullet]
    for bl in strip_trailers(c.body):
        lines.append(f"  > {bl}")
    return group, lines


def render_version_section(version, commits):
    included = [c for c in commits if not is_excluded(c.subject)]
    out = []
    date = commits[-1].date if commits else ""
    # UNVERSIONED_LABEL is a sentinel, not a semver string — rendering it
    # through the "v<version>" template would produce the malformed
    # "## vunversioned — <date>" heading (review round 1 finding #1).
    heading_name = "Unversioned" if version == UNVERSIONED_LABEL else f"v{version}"
    out.append(f"## {heading_name} — {date}")
    out.append("")

    grouped = {g: [] for g in GROUP_ORDER}
    for c in included:
        group, lines = render_entry(c)
        grouped[group].extend(lines)

    for g in GROUP_ORDER:
        if not grouped[g]:
            continue
        out.append(f"### {g}")
        out.extend(grouped[g])
        out.append("")

    return out


def generate(repo, ref="HEAD"):
    commits = first_parent_log(repo, ref)
    windows = build_version_windows(repo, commits)
    lines = ["# Changelog", "", "<!-- GENERATED by plugins/spec-workflow/scripts/changelog.py — do not edit by hand. -->", ""]
    for version, wcommits in reversed(windows):
        lines.extend(render_version_section(version, wcommits))
    # collapse trailing blank-line runs to a single trailing newline
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def cmd_generate(argv):
    repo = None
    output = None
    ref = "HEAD"
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--repo":
            i += 1
            repo = argv[i]
        elif a == "--output":
            i += 1
            output = argv[i]
        elif a == "--ref":
            i += 1
            ref = argv[i]
        else:
            sys.stderr.write(f"changelog.py generate: unknown argument {a!r}\n")
            return 2
        i += 1
    if repo is None:
        proc = _run_git(".", ["rev-parse", "--show-toplevel"])
        repo = proc.stdout.decode("utf-8").strip() if proc.returncode == 0 else "."
    if output is None:
        output = os.path.join(repo, "CHANGELOG.md")

    content = generate(repo, ref)
    tmp = output + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, output)
    return 0


def _cli(argv):
    if not argv or argv[0] != "generate":
        sys.stderr.write("usage: changelog.py generate [--repo <path>] [--output <path>]\n")
        return 2
    return cmd_generate(argv[1:])


if __name__ == "__main__":
    sys.exit(_cli(sys.argv[1:]))
